language: cpp
branches:
  only:
    - master
    - /v.*/
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:beineri/opt-qt595-xenial"
          packages:
            - g++-7 qt59base qt59svg freeglut3-dev libglew-dev mesa-common-dev build-essential libglm-dev libxxf86vm-dev libfreeimage-dev pandoc cmake p7zip-full ninja-build xvfb rpm cppcheck
    - os: linux
      dist: xenial
      env: TB_GCC8=true
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:beineri/opt-qt595-xenial"
          packages:
            - g++-8 qt59base qt59svg freeglut3-dev libglew-dev mesa-common-dev build-essential libglm-dev libxxf86vm-dev libfreeimage-dev pandoc cmake p7zip-full ninja-build xvfb rpm cppcheck
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode11.3
      env: TB_DEBUG_BUILD=true
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-macos.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux.sh; fi
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: "W2j2h2gKveogAS9u8zxavzjCPHtPBXpbDVw9Swyvn9idyeqTbeOM+uzww7MkqakIbjGrMhQdfJiCoVC3qQCw5QLybvtBWYjdHGtkq4m9F9WFmGQ4/tSOZEzvz6VNkQmGPOuRzyHWFFZQtbAn9OmJrPgjI8LrWUUubmlQ5304jnQ="
  file:
    - "build/*.deb"
    - "build/*.rpm"
    - "build/*.dmg"
    - "build/*.md5"
  on:
    repo: kduske/TrenchBroom
    tags: true
    condition: $TB_DEBUG_BUILD != 'true' && $TB_GCC8 != 'true'
