language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-macos.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux.sh; fi
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: "W2j2h2gKveogAS9u8zxavzjCPHtPBXpbDVw9Swyvn9idyeqTbeOM+uzww7MkqakIbjGrMhQdfJiCoVC3qQCw5QLybvtBWYjdHGtkq4m9F9WFmGQ4/tSOZEzvz6VNkQmGPOuRzyHWFFZQtbAn9OmJrPgjI8LrWUUubmlQ5304jnQ="
  file:
    - "build/*.deb"
    - "build/*.rpm"
    - "build/*.dmg"
    - "build/*.sha"
  on:
    repo: kduske/TrenchBroom
    tags: true
