name: Pull request
# This workflow is triggered on pull requests for the repository.
on: [pull_request]

jobs:
  clean_commit_job:
    name: Check commits for bad words
    runs-on: ubuntu-latest
    steps:
      - name: Clean commit step
        uses: TrenchBroom/clean-commit-action@v0.6.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
